FROM python:3

RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean

RUN apt-get install -y \
    libffi-dev \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zlib1g-dev \
    net-tools \
    vim \
    nano

RUN mkdir -p /var/www/descargador

WORKDIR /var/www/descargador

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

EXPOSE 8000

STOPSIGNAL SIGINT

ENTRYPOINT ["python", "manage.py"]

CMD ["runserver", "0.0.0.0:8000"]