# Generated by Django 2.1.5 on 2019-04-15 15:22

import descargadorweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descargadorweb', '0003_auto_20190125_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetededescarga',
            name='paqueteb64',
            field=models.FileField(blank=True, null=True, upload_to=descargadorweb.models.upload_to_paquete),
        ),
    ]
