# Generated by Django 2.2 on 2020-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descargadorweb', '0004_auto_20190415_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetededescarga',
            name='id_paquete',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
