# Generated by Django 2.1.5 on 2019-01-15 21:33

import descargadorweb.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cer', models.FileField(help_text='Ingrese el archivo .cer de su E.firma o Fiel', upload_to=descargadorweb.models.upload_to_efirma, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer'])])),
                ('key', models.FileField(help_text='Ingrese el archivo .key de su E.firma o Fiel', upload_to=descargadorweb.models.upload_to_efirma, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['key'])])),
                ('contrasena', models.CharField(help_text='Ingrese la contraseña de su E.firma o Fiel', max_length=50)),
                ('not_before', models.DateTimeField(blank=True)),
                ('not_after', models.DateTimeField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteDeDescarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paquete', models.CharField(max_length=40, unique=True)),
                ('cod_estatus', models.PositiveIntegerField(choices=[(300, 'Usuario no válido'), (301, 'XML mal formado'), (302, 'Sello mal formado'), (303, 'Sello no corresponde con el RFC del solicitante'), (304, 'Certificado revocado o caduco'), (305, 'Certificado no valido'), (5000, 'Solicitud recibida con exito'), (5001, 'Tercero no autorizado'), (5002, 'Agoto solicitudes de por vida'), (5003, 'Tope máximo'), (5004, 'No se encontró la información'), (5005, 'Solicitud duplicada'), (5008, 'Máximo de descargas permitidas'), (404, 'Error no encontrado')])),
                ('mensaje', models.CharField(max_length=50)),
                ('paquete', models.FileField(blank=True, null=True, upload_to=descargadorweb.models.upload_to_paquete)),
                ('fecha_descarga', models.DateTimeField(blank=True, default=None, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDeDescarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.UUIDField(unique=True)),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('rfc_receptor', models.CharField(blank=True, max_length=13, null=True)),
                ('rfc_emisor', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo_solicitud', models.CharField(choices=[('CFDI', 'CFDI'), ('Metadata', 'Metadata')], max_length=8)),
                ('cod_estatus', models.PositiveIntegerField(choices=[(300, 'Usuario no válido'), (301, 'XML mal formado'), (302, 'Sello mal formado'), (303, 'Sello no corresponde con el RFC del solicitante'), (304, 'Certificado revocado o caduco'), (305, 'Certificado no valido'), (5000, 'Solicitud recibida con exito'), (5001, 'Tercero no autorizado'), (5002, 'Agoto solicitudes de por vida'), (5003, 'Tope máximo'), (5004, 'No se encontró la información'), (5005, 'Solicitud duplicada'), (5008, 'Máximo de descargas permitidas'), (404, 'Error no encontrado')])),
                ('mensaje', models.CharField(max_length=50)),
                ('estado_solicitud', models.PositiveIntegerField(choices=[(1, 'Aceptada'), (2, 'En proceso'), (3, 'Terminada'), (4, 'Error'), (5, 'Rechazada'), (6, 'Vencida')])),
                ('numero_cfdis', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('fecha_ultima_verificacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, default=None, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descargadorweb.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionSolicitudDeDescarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_verificacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('cod_estatus', models.PositiveIntegerField(choices=[(300, 'Usuario no válido'), (301, 'XML mal formado'), (302, 'Sello mal formado'), (303, 'Sello no corresponde con el RFC del solicitante'), (304, 'Certificado revocado o caduco'), (305, 'Certificado no valido'), (5000, 'Solicitud recibida con exito'), (5001, 'Tercero no autorizado'), (5002, 'Agoto solicitudes de por vida'), (5003, 'Tope máximo'), (5004, 'No se encontró la información'), (5005, 'Solicitud duplicada'), (5008, 'Máximo de descargas permitidas'), (404, 'Error no encontrado')])),
                ('mensaje', models.CharField(max_length=50)),
                ('cod_estatus_solicitud', models.PositiveIntegerField(choices=[(300, 'Usuario no válido'), (301, 'XML mal formado'), (302, 'Sello mal formado'), (303, 'Sello no corresponde con el RFC del solicitante'), (304, 'Certificado revocado o caduco'), (305, 'Certificado no valido'), (5000, 'Solicitud recibida con exito'), (5001, 'Tercero no autorizado'), (5002, 'Agoto solicitudes de por vida'), (5003, 'Tope máximo'), (5004, 'No se encontró la información'), (5005, 'Solicitud duplicada'), (5008, 'Máximo de descargas permitidas'), (404, 'Error no encontrado')])),
                ('estado_solicitud', models.PositiveIntegerField(choices=[(1, 'Aceptada'), (2, 'En proceso'), (3, 'Terminada'), (4, 'Error'), (5, 'Rechazada'), (6, 'Vencida')])),
                ('numero_cfdis', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('solicitud_de_descarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descargadorweb.SolicitudDeDescarga')),
            ],
        ),
        migrations.AddField(
            model_name='paquetededescarga',
            name='solicitud_de_descarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descargadorweb.SolicitudDeDescarga'),
        ),
    ]
