# Generated by Django 2.1.5 on 2019-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descargadorweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
