# Generated by Django 2.1.5 on 2019-01-25 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descargadorweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paquetededescarga',
            name='cod_estatus',
            field=models.PositiveIntegerField(blank=True, choices=[(300, 'Usuario no válido'), (301, 'XML mal formado'), (302, 'Sello mal formado'), (303, 'Sello no corresponde con el RFC del solicitante'), (304, 'Certificado revocado o caduco'), (305, 'Certificado no valido'), (5000, 'Solicitud recibida con exito'), (5001, 'Tercero no autorizado'), (5002, 'Agoto solicitudes de por vida'), (5003, 'Tope máximo'), (5004, 'No se encontró la información'), (5005, 'Solicitud duplicada'), (5008, 'Máximo de descargas permitidas'), (404, 'Error no encontrado')], null=True),
        ),
        migrations.AlterField(
            model_name='paquetededescarga',
            name='solicitud_de_descarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='descargadorweb.SolicitudDeDescarga'),
        ),
        migrations.AlterField(
            model_name='solicituddedescarga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='descargadorweb.Empresa'),
        ),
        migrations.AlterField(
            model_name='verificacionsolicituddedescarga',
            name='solicitud_de_descarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='descargadorweb.SolicitudDeDescarga'),
        ),
    ]
